theme: minima
title: "About me"
Description: "Computer Science Student • Creator • Problem Solver"

author:
  name: Anis Golriz
  email: anisgolriz714@gmail.com
social:
  links:
    -"https://www.linkedin.com/in/anisgolriz/"
