theme: minima
title: "About me"
description: "Computer Science Student • Creator • Problem Solver"

author: "Anis Golriz - anisgolriz714@gmail.com"
social:
  links:
    -"https://www.linkedin.com/in/anisgolriz/"
